# Generated by Django 5.0.6 on 2024-11-01 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
                ('responses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respones', to='network.commentresponse')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=256)),
                ('hashtags', models.TextField(max_length=64)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=64)),
                ('image', models.ImageField(max_length=64, upload_to='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
