# Generated by Django 5.0.6 on 2024-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_posts_image_posts_media_user_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='titlepic',
            field=models.FileField(max_length=64, null=True, upload_to='title_pic'),
        ),
    ]
