# Generated by Django 5.0.6 on 2024-11-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_titlepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.posts'),
        ),
        migrations.AddField(
            model_name='commentresponse',
            name='Comment',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='respones', to='network.comment'),
        ),
    ]
