# Generated by Django 5.0.6 on 2024-11-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_comment_responses_remove_posts_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='hashtags',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
